export const GET_GAME_EVENT_REQUEST = "GET_GAME_EVENT_REQUEST";
export const GET_GAME_EVENT_SUCCESS = "GET_GAME_EVENT_SUCCESS";
export const GET_GAME_EVENT_FAILURE = "GET_GAME_EVENT_FAILURE";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const GET_ADDTOCART_SUCCESS = "GET_ADDTOCART_SUCCESS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const POST_CHECKOUT_REQUEST = "POST_CHECKOUT_REQUEST";
export const POST_CHECKOUT_SUCCESS = "POST_CHECKOUT_SUCCESS";
export const POST_CHECKOUT_FAILURE = "POST_CHECKOUT_FAILURE";
